README.md
flake.nix
rust-overlay.nix

This helps nightly users from manually selecting date having some components available.
Related: #34 #14

Add helper `selectLatestNightlyWith` and tweak docs

---

rust-overlay.nix

It seems like there has been a mixup on what the build, host and target platforms are. To
quote the Nixpkgs manual: "In summary, build is the platform on which a package is being
built, host is the platform on which it will run. The third attribute, target, is relevant
only for certain specific compilers and build tools."
This is what I think was intended and lets us successfully cross compile from linux and
macOS to WASI and Windows, something that was broken before where native dependencies would leak into the cross-compile.
Fixes #40

Fix cross-compilation

---

README.md

The readme says to not use `rust-bin.nightly.latest`, but the readme used `rust-bin.nightly.latest`.
Not anymore.

readme: Don't use rust-bin.nightly.latest

---

rust-overlay.nix

value is a string while a list was expected

typo in comments

---

.github/workflows/ci.yaml
default.nix
docs/reference.md
flake.lock
flake.nix
lib.nix
manifest.nix
systems.nix

- Drops flake-utils and follows https://github.com/nix-systems/nix-systems to allow overriding systems.
- Split the overlay interface from packaging/toolchain-selection logic.
- Avoid the need of `import nixpkgs`, as stated in #94
It would be good to export functions in `lib.nix` under `lib` flake output. But it's not easy since `select*` depends on unpacked `manifests`, which depends on `pkgs`. Using interface `lib.select* = pkgs: <drv>` would unpack manifests every time when called.

Rework flake and overlay structures

---

mk-aggregated.nix

A copy of librustc_driver is installed into `lib/rustlib/$target/lib` with rustc-dev. This is added to `LD_LIBRARY_PATH` by Cargo when it executes build scripts. Without this fix, rustc triggered from build scripts would see the wrong sysroot.
This extends be3a8a8b59aaec5cd96d3ea6e4470bd14bdd8b37 to cover the additional case.
Use this `build.rs`:
```rust
use std::process::Command;
fn main() {
let ld_library_path = std::env::var("LD_LIBRARY_PATH").unwrap_or_default();
eprintln!("LD_LIBRARY_PATH={}", ld_library_path);
let sysroot = Command::new("rustc")
.args(&["--print", "sysroot"])
.output()
.unwrap();
let sysroot = std::str::from_utf8(&sysroot.stdout).unwrap().trim();
eprintln!("  Actual sysroot: {}", sysroot);
let sysroot_no_path = Command::new("rustc")
.args(&["--print", "sysroot"]) …
```

mk-aggregated: Also dereference librustc_driver in rustlib

---

mk-aggregated.nix

The Cargo bundled in this project links against the operating system's libcurl. This can be demonstrated with
```
$ otool -L $(which cargo)
/nix/store/s8rb4j0rh3wm66r4hmgj4axcic321bak-rust-default-1.73.0/bin/cargo:
/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 60420.101.2)
/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1971.0.0)
/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 9.0.0)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.100.3)
```
The system's libcurl dynamically depends on the system's libcrypto. On MacOS …

fix sandbox builds on ventura

---

README.md

Mismatched versions of nixpkgs [can cause bugs with certain packages](https://github.com/tauri-apps/tauri/issues/8254).

Fix mistake in nixos configuration documentation

---

mk-aggregated.nix

It came out of [debugging a call to `overrideSDK` on a x86_64-darwin system on the Nix discourse](https://discourse.nixos.org/t/need-help-from-darwin-users-syntax-errors-in-library-frameworks-foundation-framework-headers/30467/8?u=jost-s), that the rust-overlay returns a nested list with `libiconv` as the only element. That caused the override to fail.
`lib.optional` takes any value and puts it into a list when the condition is met. In this case the value is wrapped in a list, so the result is a nested list.
```sh
nix-repl> legacyPackages.aarch64-darwin.lib.optional true ""                                       
[ "" ]
nix-repl> legacyPackages.aarch64-darwin.lib.optional true [""]
[ [ ... ] ]
```
I suggest to return a flat list instead, as is done a few lines up in the same file.

Return target dep as flat list instead of nested list for darwin std

---

README.md

relocated the ```with pkgs;``` statement to its typical location within the devshell.default assignment. This is a very minor change merely improving cohesion and nothing else

Update README.md to narrow pkgs scope in nix develop segment

---

.github/workflows/ci.yaml
ld-wrapper.sh
mk-aggregated.nix
mk-component-set.nix

Upstream-shipped `rust-ld` is now used as default linker for some targets on nightly. It needs ld-wrapper for interopation with libraries from Nix. Currently `wrapBintools` interface is uneasy for hook use inside a derivation also containing non-bintools stuff. We hereby copy part of the implementation and wrap `rust-ld` in-place.
See: https://github.com/rust-lang/rust/issues/71515#issuecomment-2116969162
Fixes #168
External library linking is now working correct. Previously it compiles but the binary fails to run.
```console
$ echo '#[link(name = "crypt")] extern "C" { fn crypt(); } fn main() { dbg!(crypt as unsafe extern "C" fn()); }' >test.rs
$ nix build -f ./repl.nix rust-bin.nightly.2024-05-27.minimal
$ nix-shell -p libxcrypt --run './result/bin/rustc test.rs'
$ ./test
[test.rs:3:13] …
```

mk-component-set: apply ld-wrapper for rust-ld

---

flake.nix

To remove the warning on `nix flake check`.

flake: remove compatibility with nix < 2.7 layout

---

lib/mk-aggregated.nix

The original binary may have outstanding RPATH, eg. to libgcc_s, which must be kept.
Fixes #161

mk-aggregated: prepend rpath instead of setting it

---

flake.lock
flake.nix
tests/default.nix

- Tests are moved out into `tests/default.nix`.
- flake-utils dependency is dropped.
- Exposed flake systems (`builtins.attrNames packages`) now follow `nixpkgs.lib.systems.flakeExposed`, since we depends on nixpkgs anyway. Custom systems can still be used via [`mkRustBin` interface](https://github.com/oxalica/rust-overlay/blob/8717107781e6bf0e7a15fc136149df940ffb5722/docs/reference.md).
Closes #179.

flake: refactor and drop flake-utils dependency

---

examples/cross-aarch64/flake.nix

This avoids manual package spliting and should be more user-friendly.

examples: also use callPackage for flake

---

lib/mk-aggregated.nix
lib/mk-component-set.nix

On Linux, the recommended way to work with `cargo login` is via libsecret, but that requires a specific LD_LIBRARY_PATH with this overaly.
This PR fixes this by adding libsecret as a runtime dependency of cargo.
Tested on Linux-aarch64.

Adding libsecret to cargo to get `cargo login` to work

---

flake.lock
lib/mk-aggregated.nix

Inherit passthru platforms from nixpkgs' rustc to fix for latest nixpkgs

---

lib/mk-component-set.nix

Fixes #195
Upstream change: NixOS/nixpkgs#351315

mk-component-set: fix for latest nixpkgs' darwin handling

---

.github/workflows/ci.yaml
default.nix
examples/cross-wasi/Makefile
examples/cross-wasi/shell.nix
flake.lock
flake.nix
lib/rust-bin.nix

The un-versioned `wasm32-wasi` target is removed in favor of `wasm32-wasip?` since Rust 1.84. Examples are updated.
The nixpkgs patch for WASI target name remapping is merged in 24.11. We can also safely remove the workaround.

Remove WASI target workaround and fix example in CI

---

lib/mk-component-set.nix

This would fix #203
Some open questions for me:
- Are these all components one might be interested in?
- I only added them here conservatively, as if its wrong `getExe` will still happily interpolate the wrong name and it will then give weird errors of non-existent binaries
- How could this be made more maintainable?
I tried to not over-complicate it, but due to the fact that the renames table has its renaming in a more declarative style, its hard to get the information out of it in a straightforward way.
- An alternative could be to add the meta attribute in an `overrideAttr` in the last step of `mkComponentSet`. As we have access to the 'correct' name.
- Another way could be to introduce another mapping from `component -> <executable name>`. This would be the least error-prone. But I am …

Add meta.mainProgram for select components

---

docs/cross_compilation.md

I noticed that the nix code block under the flakes section in `docs/cross_compilation.md` is missing the crucial `pkgs.callPackage`-part. It is explained above in the non-flake-section, and also used in the actual example flake that is referenced below (although without explanation), but missing here.
This really confused me, as I skipped the non-flakes-section, as I knew I wanted a flake solution, looked at the examples, did not understand the seemingly-redundant `pkgs.callPackage` call, left it out in my own project's flake and then wondered why it doesn't work. I only later realized the importance of this `pkgs.callPackage` call, and also that it was documented in the non-flakes-section, which I skipped.
So hopefully this will save someone from reliving what just happened to me.

Make cross compilation flake example follow code more closely
